/** Re-export standalone layout tokens for embed routes. */
export {
  STANDALONE_CHAT_INPUT_WRAPPER_CLASS as EMBED_CHAT_INPUT_WRAPPER_CLASS,
  STANDALONE_FOOTER_INNER_CLASS as EMBED_FOOTER_INNER_CLASS,
  STANDALONE_FOOTER_OUTER_CLASS as EMBED_FOOTER_OUTER_CLASS,
  STANDALONE_MESSAGES_COLUMN_CLASS as EMBED_MESSAGES_COLUMN_CLASS,
} from '@/lib/standalone-layout';
